version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    expose:
      - "4173"
    environment:
      - VITE_API_URL=https://themuseummap.net/api
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    expose:
      - "3001"
    volumes:
      - ./backend/uploads:/app/uploads
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/arqueodb
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=arqueodb

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./uploads:/app/uploads
    depends_on:
      - frontend
      - backend

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: > 
      sh -c "sleep 10 && certbot certonly --webroot --webroot-path=/var/www/certbot 
      --email tuemail@correo.com --agree-tos --no-eff-email 
      -d themuseummap.net && nginx -s reload"
      
volumes:
  postgres_data:
