# renew_before_expiry = 30 days
version = 4.1.1
archive_dir = /etc/letsencrypt/archive/themuseummap.net
cert = /etc/letsencrypt/live/themuseummap.net/cert.pem
privkey = /etc/letsencrypt/live/themuseummap.net/privkey.pem
chain = /etc/letsencrypt/live/themuseummap.net/chain.pem
fullchain = /etc/letsencrypt/live/themuseummap.net/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = 742570c9693cb66ea4b6670ae3dd4404
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
themuseummap.net = /var/www/certbot
